// Code generated by ogen, DO NOT EDIT.

package procountorapi

import (
	"fmt"
	"hash/fnv"
)

// Hash computes a hash value for AccountingReportRow using FNV-1a.
// Equal objects must produce equal hashes.
func (a AccountingReportRow) Hash() uint64 {
	h := fnv.New64a()

	// Hash optional field: RowId
	if a.RowId.Set {
		h.Write([]byte{1})
		h.Write([]byte(fmt.Sprintf("%v", a.RowId.Value)))
	} else {
		h.Write([]byte{0})
	}
	// Hash optional field: Type
	if a.Type.Set {
		h.Write([]byte{1})
		h.Write([]byte(fmt.Sprintf("%v", a.Type.Value)))
	} else {
		h.Write([]byte{0})
	}
	// Hash optional field: Name
	if a.Name.Set {
		h.Write([]byte{1})
		h.Write([]byte(fmt.Sprintf("%v", a.Name.Value)))
	} else {
		h.Write([]byte{0})
	}
	// Hash optional field: Value
	if a.Value.Set {
		h.Write([]byte{1})
		h.Write([]byte(fmt.Sprintf("%v", a.Value.Value)))
	} else {
		h.Write([]byte{0})
	}
	// Hash optional field: Formula
	if a.Formula.Set {
		h.Write([]byte{1})
		h.Write([]byte(fmt.Sprintf("%v", a.Formula.Value)))
	} else {
		h.Write([]byte{0})
	}
	return h.Sum64()
}
