// Code generated by ogen, DO NOT EDIT.

package procountorapi

import "github.com/ogen-go/ogen/validate"

// Equal compares two LedgerAccountsReportRow instances for equality.
// The depth parameter prevents infinite recursion on nested objects.
func (a LedgerAccountsReportRow) Equal(b LedgerAccountsReportRow, depth int) bool {
	if depth > 10 {
		panic(&validate.DepthLimitError{
			MaxDepth: 10,
			TypeName: "LedgerAccountsReportRow",
		})
	}

	// Compare optional field: Name
	if a.Name.Set != b.Name.Set {
		return false
	}
	if a.Name.Set {
		if a.Name.Value != b.Name.Value {
			return false
		}
	}
	// Compare optional field: Value
	if a.Value.Set != b.Value.Set {
		return false
	}
	if a.Value.Set {
		if a.Value.Value != b.Value.Value {
			return false
		}
	}
	return true
}
