// Code generated by ogen, DO NOT EDIT.

package procountorapi

// setDefaults set default value of fields.
func (s *AccountingReportRequestOptions) setDefaults() {
	{
		val := string("EUR")
		s.TransactionCurrency.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *BusinessPartnerAdditionalInfo) setDefaults() {
	{
		val := BusinessPartnerAdditionalInfoInvoiceLedger("INVOICE_LEDGER")
		s.InvoiceLedger.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *GeneralLedgerReportRequestOptions) setDefaults() {
	{
		val := string("EUR")
		s.TransactionCurrency.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *LedgerAccountsReportRequestOptions) setDefaults() {
	{
		val := string("EUR")
		s.TransactionCurrency.SetTo(val)
	}
}
