// Code generated by ogen, DO NOT EDIT.

package procountorapi

import "github.com/ogen-go/ogen/validate"

// Equal compares two AccountingReportRow instances for equality.
// The depth parameter prevents infinite recursion on nested objects.
func (a AccountingReportRow) Equal(b AccountingReportRow, depth int) bool {
	if depth > 10 {
		panic(&validate.DepthLimitError{
			MaxDepth: 10,
			TypeName: "AccountingReportRow",
		})
	}

	// Compare optional field: RowId
	if a.RowId.Set != b.RowId.Set {
		return false
	}
	if a.RowId.Set {
		if a.RowId.Value != b.RowId.Value {
			return false
		}
	}
	// Compare optional field: Type
	if a.Type.Set != b.Type.Set {
		return false
	}
	if a.Type.Set {
		if a.Type.Value != b.Type.Value {
			return false
		}
	}
	// Compare optional field: Name
	if a.Name.Set != b.Name.Set {
		return false
	}
	if a.Name.Set {
		if a.Name.Value != b.Name.Value {
			return false
		}
	}
	// Compare optional field: Value
	if a.Value.Set != b.Value.Set {
		return false
	}
	if a.Value.Set {
		if a.Value.Value != b.Value.Value {
			return false
		}
	}
	// Compare optional field: Formula
	if a.Formula.Set != b.Formula.Set {
		return false
	}
	if a.Formula.Set {
		if a.Formula.Value != b.Formula.Value {
			return false
		}
	}
	return true
}
