// Code generated by ogen, DO NOT EDIT.

package procountorapi

// AddDimensionItemParams is parameters of addDimensionItem operation.
type AddDimensionItemParams struct {
	// Dimension identifier.
	DimensionId int
}

// AddNotesToInvoiceParams is parameters of addNotesToInvoice operation.
type AddNotesToInvoiceParams struct {
	// Invoice identifier.
	InvoiceId int
}

// ApproveInvoiceParams is parameters of approveInvoice operation.
type ApproveInvoiceParams struct {
	// Invoice identifier.
	InvoiceId int
	// Enable inventory management update.
	UpdateInventory OptBool `json:",omitempty,omitzero"`
}

// ApproveLedgerReceiptParams is parameters of approveLedgerReceipt operation.
type ApproveLedgerReceiptParams struct {
	// Ledger receipt identifier.
	ReceiptId int
}

// DeleteAttachmentParams is parameters of deleteAttachment operation.
type DeleteAttachmentParams struct {
	// ID of the attachment.
	AttachmentId int
}

// GetAttachmentContentParams is parameters of getAttachmentContent operation.
type GetAttachmentContentParams struct {
	AttachmentId int
}

// GetBusinessPartnerParams is parameters of getBusinessPartner operation.
type GetBusinessPartnerParams struct {
	// ID of the business partner.
	ID string
}

// GetCommentByIdParams is parameters of getCommentById operation.
type GetCommentByIdParams struct {
	// Invoice identifier.
	InvoiceId int
	// ID of the comment.
	CommentId int
}

// GetCostCenterParams is parameters of getCostCenter operation.
type GetCostCenterParams struct {
	LedgerReceiptId int
}

// GetCostReceiptParams is parameters of getCostReceipt operation.
type GetCostReceiptParams struct {
	CostReceiptId int
}

// GetDefaultAccountsParams is parameters of getDefaultAccounts operation.
type GetDefaultAccountsParams struct {
	// ID of the business partner.
	ID int
}

// GetDimensionParams is parameters of getDimension operation.
type GetDimensionParams struct {
	// Dimension identifier.
	DimensionId int
}

// GetDimensionsParams is parameters of getDimensions operation.
type GetDimensionsParams struct {
	// Name of the dimension. Supports partial search.
	Name OptString `json:",omitempty,omitzero"`
	// Name of the dimension item. Supports partial search.
	CodeName OptString `json:",omitempty,omitzero"`
}

// GetGeneralLedgerReportParams is parameters of getGeneralLedgerReport operation.
type GetGeneralLedgerReportParams struct {
	// Ledger account code identifier.
	ID int
}

// GetInvoiceParams is parameters of getInvoice operation.
type GetInvoiceParams struct {
	// ID of the invoice.
	InvoiceId string
}

// GetInvoiceCommentsParams is parameters of getInvoiceComments operation.
type GetInvoiceCommentsParams struct {
	// If true, only those comments that have tagged users and comments have been read by all tagged
	// users are returned. Comments without tagged users aren't returned. If false, only those comments
	// that have tagged users but comments have not been read by all tagged users are returned. Comments
	// without tagged users aren't returned.
	ReadByAllTaggedUsers OptBool `json:",omitempty,omitzero"`
	// Invoice identifier.
	InvoiceId int
}

// GetInvoiceImageParams is parameters of getInvoiceImage operation.
type GetInvoiceImageParams struct {
	// The invoice page number.
	Page OptInt `json:",omitempty,omitzero"`
	// Invoice image format.
	Format OptGetInvoiceImageFormat `json:",omitempty,omitzero"`
	// Invoice identifier.
	InvoiceId int
}

// GetInvoiceTransactionsParams is parameters of getInvoiceTransactions operation.
type GetInvoiceTransactionsParams struct {
	// Invoice identifier.
	InvoiceId int
}

// GetInvoicesForPersonalApprovalsParams is parameters of getInvoicesForPersonalApprovals operation.
type GetInvoicesForPersonalApprovalsParams struct {
	// Invoice type.
	Types GetInvoicesForPersonalApprovalsTypes
}

// GetInvoicesForPersonalVerificationsParams is parameters of getInvoicesForPersonalVerifications operation.
type GetInvoicesForPersonalVerificationsParams struct {
	// Invoice type.
	Types GetInvoicesForPersonalVerificationsTypes
}

// GetLedgerReceiptParams is parameters of getLedgerReceipt operation.
type GetLedgerReceiptParams struct {
	// Ledger receipt identifier.
	ReceiptId string
}

// GetPartnerGroupParams is parameters of getPartnerGroup operation.
type GetPartnerGroupParams struct {
	// ID of the partner group.
	ID int
}

// GetPartnerGroupsParams is parameters of getPartnerGroups operation.
type GetPartnerGroupsParams struct {
	// Business partner group name. Uses substring matching.
	Name OptString `json:",omitempty,omitzero"`
	// Business partner group type.
	Type OptGetPartnerGroupsType `json:",omitempty,omitzero"`
	// Status of business partner group.
	Active OptBool `json:",omitempty,omitzero"`
	// Page size for the results. Maximum value: 200.
	Size OptInt `json:",omitempty,omitzero"`
	// Page number for the results.
	Page OptInt `json:",omitempty,omitzero"`
}

// GetPaymentEventByIdAndInvoiceIdParams is parameters of getPaymentEventByIdAndInvoiceId operation.
type GetPaymentEventByIdAndInvoiceIdParams struct {
	// Invoice identifier.
	InvoiceId int
	// Payment event identifier.
	PaymentEventId int
}

// GetPersonByIdParams is parameters of getPersonById operation.
type GetPersonByIdParams struct {
	// Id of the person.
	ID int
}

// GetPersonsParams is parameters of getPersons operation.
type GetPersonsParams struct {
	// Person number Also partial - search matches returned.
	PersonNumber OptString `json:",omitempty,omitzero"`
	// Main group name of type PERSON Only exact - search match returned.
	MainPersonGroup OptString `json:",omitempty,omitzero"`
	// Unique identifier of Business Partner Group of type PERSON.
	PersonGroupId OptInt `json:",omitempty,omitzero"`
	// Include inactive persons.
	IncludeInactive OptBool `json:",omitempty,omitzero"`
	// Page size for the results. Maximum value: 200.
	Size OptInt `json:",omitempty,omitzero"`
	// Page number for the results.
	Page OptInt `json:",omitempty,omitzero"`
	// Order the results by Person ID.
	OrderById OptGetPersonsOrderById `json:",omitempty,omitzero"`
}

// GetTaggeableUsersParams is parameters of getTaggeableUsers operation.
type GetTaggeableUsersParams struct {
	// Invoice identifier.
	InvoiceId int
}

// GetVatStatusesForCountryParams is parameters of getVatStatusesForCountry operation.
type GetVatStatusesForCountryParams struct {
	// Country code in ISO 3166-1 alpha-2 format.
	CountryCode string
}

// ListProductsParams is parameters of listProducts operation.
type ListProductsParams struct {
	// Product group.
	Group string
}

// MarkInvoiceAsInvalidatedParams is parameters of markInvoiceAsInvalidated operation.
type MarkInvoiceAsInvalidatedParams struct {
	// Invoice identifier.
	InvoiceId int
}

// MarkInvoiceAsPaidParams is parameters of markInvoiceAsPaid operation.
type MarkInvoiceAsPaidParams struct {
	// Supported only for SALES_INVOICE type. Default is false. When marking the overdue sales invoice as
	// paid, if you want to automatically include a penal expense in the business partner's next sales
	// invoice, then call the endpoint with addPenalExpense=true. Automatic handling of collection and
	// penal costs setting must be enabled prior to this and penal expense product must be already
	// defined.
	AddPenalExpense OptBool `json:",omitempty,omitzero"`
	// Invoice identifier.
	InvoiceId int
}

// MarkInvoiceAsUnfinishedParams is parameters of markInvoiceAsUnfinished operation.
type MarkInvoiceAsUnfinishedParams struct {
	// Invoice identifier.
	InvoiceId int
}

// MarkLedgerReceiptAsInvalidatedParams is parameters of markLedgerReceiptAsInvalidated operation.
type MarkLedgerReceiptAsInvalidatedParams struct {
	// Ledger receipt identifier.
	ReceiptId int
}

// MarkLedgerReceiptAsUnfinishedParams is parameters of markLedgerReceiptAsUnfinished operation.
type MarkLedgerReceiptAsUnfinishedParams struct {
	// Ledger receipt identifier.
	ReceiptId int
}

// PutBusinessPartnerParams is parameters of putBusinessPartner operation.
type PutBusinessPartnerParams struct {
	// Business partner identifier.
	ID int
}

// RejectInvoiceParams is parameters of rejectInvoice operation.
type RejectInvoiceParams struct {
	// Invoice identifier.
	InvoiceId int
}

// RemovePaymentEventParams is parameters of removePaymentEvent operation.
type RemovePaymentEventParams struct {
	// Invoice identifier.
	InvoiceId int
	// Payment identifier.
	PaymentEventId int
}

// RenameAttachmentParams is parameters of renameAttachment operation.
type RenameAttachmentParams struct {
	// Name of the attachment file.
	Name OptString `json:",omitempty,omitzero"`
	// ID of the attachment.
	AttachmentId int
}

// SaveInvoiceParams is parameters of saveInvoice operation.
type SaveInvoiceParams struct {
	// Supported only for SALES_INVOICE type. Default is false. If true, automatically adds the
	// collection cost(s), if payment reminders were sent earlier to the business partner and/or penal
	// cost, if the business partner had paid the earlier invoice late. These costs are added only if
	// Automatic handling of collection and penal costs setting is enabled, and collection costs product
	// and penal expense product have been defined.
	AddCollectionPenalCosts OptBool `json:",omitempty,omitzero"`
}

// SaveInvoiceCommentParams is parameters of saveInvoiceComment operation.
type SaveInvoiceCommentParams struct {
	// Invoice identifier.
	InvoiceId int
}

// SaveLedgerReceiptParams is parameters of saveLedgerReceipt operation.
type SaveLedgerReceiptParams struct {
	// Enable automatic generation of reconciliation row.
	CreateReconciliation OptBool `json:",omitempty,omitzero"`
}

// SearchBusinessPartnersParams is parameters of searchBusinessPartners operation.
type SearchBusinessPartnersParams struct {
	// Business identifier type of the partner.
	IdentifierType OptString `json:",omitempty,omitzero"`
	// Customer number.
	CustomerNumber OptString `json:",omitempty,omitzero"`
	// Main group.
	MainGroup OptString `json:",omitempty,omitzero"`
	// Business Partner Group.
	PartnerGroup OptString `json:",omitempty,omitzero"`
	// Type of business partner.
	Type OptSearchBusinessPartnersType `json:",omitempty,omitzero"`
	// Order the results by invoice ID.
	OrderById OptSearchBusinessPartnersOrderById `json:",omitempty,omitzero"`
	// Previous invoice ID for pagination.
	PreviousId OptInt `json:",omitempty,omitzero"`
	// Status of business partner.
	Active OptBool `json:",omitempty,omitzero"`
	// Start date of the search (business partner updated date).
	VersionStartDate OptDateTime `json:",omitempty,omitzero"`
	// End date of the search (business partner updated date).
	VersionEndDate OptDateTime `json:",omitempty,omitzero"`
	// Page size for the results. Maximum value: 200.
	Size OptInt `json:",omitempty,omitzero"`
	// Page number for the results.
	Page OptInt `json:",omitempty,omitzero"`
}

// SearchCostReceiptsParams is parameters of searchCostReceipts operation.
type SearchCostReceiptsParams struct {
	// Start date of the search (created date).
	CreatedStartDate OptDate `json:",omitempty,omitzero"`
}

// SearchInvoiceParams is parameters of searchInvoice operation.
type SearchInvoiceParams struct {
	// Invoice status.
	Status []SearchInvoiceStatusItem `json:",omitempty"`
	// Start date of the search (invoice billing date).
	StartDate OptDate `json:",omitempty,omitzero"`
	// End date of the search (invoice billing date).
	EndDate OptDate `json:",omitempty,omitzero"`
	// Start date of the search (invoice created date).
	CreatedStartDate OptDateTime `json:",omitempty,omitzero"`
	// End date of the search (invoice created date).
	CreatedEndDate OptDateTime `json:",omitempty,omitzero"`
	// Start date of the search (invoice updated date).
	VersionStartDate OptDateTime `json:",omitempty,omitzero"`
	// End date of the search (invoice updated date).
	VersionEndDate OptDateTime `json:",omitempty,omitzero"`
	// Start date of the search (invoice due date).
	DueStartDate OptDate `json:",omitempty,omitzero"`
	// End date of the search (invoice due date).
	DueEndDate OptDate `json:",omitempty,omitzero"`
	// Invoice types. Supports more than one invoice status, separated by comma.
	Types []SearchInvoiceTypesItem `json:",omitempty"`
	// Search invoices with given business partner ID.
	BusinessPartnerId OptInt `json:",omitempty,omitzero"`
	// Search invoices with given factoring contract Id.
	FactoringContractId OptInt `json:",omitempty,omitzero"`
	// Search invoices with given original invoice number.
	OriginalInvoiceNumber OptString `json:",omitempty,omitzero"`
	// Search invoices with given invoice number.
	InvoiceNumber OptInt `json:",omitempty,omitzero"`
	// Search invoices by searchTerm. Allows searching by counterpartyAddress.name, invoiceNumber and
	// additionalInformation.
	SearchTerm OptString `json:",omitempty,omitzero"`
	// Previous invoice ID for pagination.
	PreviousId OptInt `json:",omitempty,omitzero"`
	// Order the results by invoice ID.
	OrderById OptSearchInvoiceOrderById `json:",omitempty,omitzero"`
	// Order the results by date.
	OrderByDate OptSearchInvoiceOrderByDate `json:",omitempty,omitzero"`
	// Order the results by created date.
	OrderByCreated OptSearchInvoiceOrderByCreated `json:",omitempty,omitzero"`
	// Order the results by version (updated date).
	OrderByVersion OptSearchInvoiceOrderByVersion `json:",omitempty,omitzero"`
	// Page size for the results. Maximum value: 200.
	Size OptInt `json:",omitempty,omitzero"`
	// Page number for the results.
	Page OptInt `json:",omitempty,omitzero"`
	// Invoice channel.
	InvoiceChannel []SearchInvoiceInvoiceChannelItem `json:",omitempty"`
}

// SearchLedgerReceiptParams is parameters of searchLedgerReceipt operation.
type SearchLedgerReceiptParams struct {
	// Start date of the search (ledger receipt date).
	StartDate OptDate `json:",omitempty,omitzero"`
	// End date of the search (ledger receipt date).
	EndDate OptDate `json:",omitempty,omitzero"`
	// Start date of the search (ledger created date).
	CreatedStartDate OptDateTime `json:",omitempty,omitzero"`
	// End date of the search (ledger created date).
	CreatedEndDate OptDateTime `json:",omitempty,omitzero"`
	// Start date of the search (ledger updated date).
	VersionStartDate OptDateTime `json:",omitempty,omitzero"`
	// End date of the search (ledger updated date).
	VersionEndDate OptDateTime `json:",omitempty,omitzero"`
	// Ledger receipt types.
	Types []SearchLedgerReceiptTypesItem `json:",omitempty"`
	// Previous Id for pagination.
	PreviousId OptInt `json:",omitempty,omitzero"`
	// Order the results by ledger receipt ID.
	OrderById OptSearchLedgerReceiptOrderById `json:",omitempty,omitzero"`
	// Order the results by date.
	OrderByDate OptSearchLedgerReceiptOrderByDate `json:",omitempty,omitzero"`
	// Order the results by created date.
	OrderByCreated OptSearchLedgerReceiptOrderByCreated `json:",omitempty,omitzero"`
	// Order the results by version (updated date).
	OrderByVersion OptSearchLedgerReceiptOrderByVersion `json:",omitempty,omitzero"`
	// Page size for the results. Maximum value: 200.
	Size OptInt `json:",omitempty,omitzero"`
	// Page number for the results.
	Page OptInt `json:",omitempty,omitzero"`
	// Ledger receipt status.
	Status OptString `json:",omitempty,omitzero"`
}

// SearchPaymentEventsParams is parameters of searchPaymentEvents operation.
type SearchPaymentEventsParams struct {
	// Previous invoice ID for pagination.
	PreviousId OptInt `json:",omitempty,omitzero"`
	// Order the results by invoice ID.
	OrderById OptSearchPaymentEventsOrderById `json:",omitempty,omitzero"`
	// Page size for the results. Maximum value: 200.
	Size OptInt `json:",omitempty,omitzero"`
	// Page number for the results.
	Page OptInt `json:",omitempty,omitzero"`
	// Invoice identifier.
	InvoiceId int
}

// SendParams is parameters of send operation.
type SendParams struct {
	// Invoice identifier.
	InvoiceId int
}

// SendToCirculationParams is parameters of sendToCirculation operation.
type SendToCirculationParams struct {
	// Invoice identifier.
	InvoiceId int
}

// SetCommentReadByUserParams is parameters of setCommentReadByUser operation.
type SetCommentReadByUserParams struct {
	// Invoice identifier.
	InvoiceId int
	// ID of the comment.
	CommentId int
}

// UpdateBusinessPartnerParams is parameters of updateBusinessPartner operation.
type UpdateBusinessPartnerParams struct {
	// Business partner identifier.
	ID int
	// Business partner last modification time. It is required if not filled in the request body.
	Version OptString `json:",omitempty,omitzero"`
}

// UpdateBusinessPartnerGroupParams is parameters of updateBusinessPartnerGroup operation.
type UpdateBusinessPartnerGroupParams struct {
	// Business partner group identifier.
	ID int
}

// UpdateDimensionParams is parameters of updateDimension operation.
type UpdateDimensionParams struct {
	DimensionId int
}

// UpdateDimensionItemParams is parameters of updateDimensionItem operation.
type UpdateDimensionItemParams struct {
	// Dimension identifier.
	DimensionId int
}

// UpdateLedgerReceiptParams is parameters of updateLedgerReceipt operation.
type UpdateLedgerReceiptParams struct {
	// Enable automatic generation of reconciliation row.
	CreateReconciliation OptBool `json:",omitempty,omitzero"`
	// Ledger receipt identifier.
	ReceiptId int
}

// UpdateLedgerReceiptTransactionDimensionsParams is parameters of updateLedgerReceiptTransactionDimensions operation.
type UpdateLedgerReceiptTransactionDimensionsParams struct {
	// Ledger receipt identifier.
	ReceiptId int
	// Transaction identifier.
	TransactionId int
}

// UpdatePersonParams is parameters of updatePerson operation.
type UpdatePersonParams struct {
	// Id of the person.
	ID int
}

// VerifyInvoiceParams is parameters of verifyInvoice operation.
type VerifyInvoiceParams struct {
	// Invoice identifier.
	InvoiceId int
}
