// Code generated by ogen, DO NOT EDIT.

package procountorapi

import (
	"github.com/ogen-go/ogen/validate"
)

// validateUniqueAccountingReportRow checks for duplicate items using hash-based detection.
func validateUniqueAccountingReportRow(items []AccountingReportRow) (err error) {
	if len(items) <= 1 {
		return nil
	}

	defer func() {
		if r := recover(); r != nil {
			if e, ok := r.(*validate.DepthLimitError); ok {
				err = e
			} else {
				panic(r)
			}
		}
	}()

	type entry struct {
		item  AccountingReportRow
		index int
	}
	buckets := make(map[uint64][]entry, len(items))

	for i, item := range items {
		hash := item.Hash()
		bucket := buckets[hash]

		for _, existing := range bucket {
			if item.Equal(existing.item, 0) {
				return &validate.DuplicateItemsError{
					Indices: []int{existing.index, i},
				}
			}
		}

		buckets[hash] = append(bucket, entry{item: item, index: i})
	}

	return nil
}

// validateUniqueLedgerAccountsReportRow checks for duplicate items using hash-based detection.
func validateUniqueLedgerAccountsReportRow(items []LedgerAccountsReportRow) (err error) {
	if len(items) <= 1 {
		return nil
	}

	defer func() {
		if r := recover(); r != nil {
			if e, ok := r.(*validate.DepthLimitError); ok {
				err = e
			} else {
				panic(r)
			}
		}
	}()

	type entry struct {
		item  LedgerAccountsReportRow
		index int
	}
	buckets := make(map[uint64][]entry, len(items))

	for i, item := range items {
		hash := item.Hash()
		bucket := buckets[hash]

		for _, existing := range bucket {
			if item.Equal(existing.item, 0) {
				return &validate.DuplicateItemsError{
					Indices: []int{existing.index, i},
				}
			}
		}

		buckets[hash] = append(bucket, entry{item: item, index: i})
	}

	return nil
}
